In [2]:
#importing the libraries for data preprocessing and tranformation
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [3]:
#this dataset contains the over by over data of all matches in ipl 2016
df = pd.read_csv("ipl_overs_data_extra.csv")

In [4]:
#one hot encoding the categorical variables
df_2 = pd.get_dummies(df, columns=["Home_Team","Away_Team","Toss_Won","Toss_Decision","Venue","Batting_Team"], drop_first=True)

In [5]:

df_2.to_csv("encoded1.csv")

In [6]:
#contains the batsman cluster numbers that we computed in PHASE 1 using KMeansClustering
data = pd.read_csv("batcluster1.csv",usecols=["Name","class"])

In [7]:
batclust = data.set_index("Name").T.to_dict('list')

In [8]:
#contains the bowler cluster numbers that we computed in PHASE 1 using KMeansClustering
for i in batclust.keys():
    batclust[i] = batclust[i][0]

In [9]:
dat = pd.read_csv("bowlcluster.csv",usecols=["Name","class"])

In [10]:
bowlclust = dat.set_index("Name").T.to_dict('list')
for i in bowlclust.keys():
    bowlclust[i] = bowlclust[i][0]
dfr = df_2.replace({"Striker":batclust,"Non_Striker":batclust,"Bowler":bowlclust})
dfr.to_csv("finalenc1.csv")

In [11]:
dfr

,Over,Striker,Non_Striker,Bowler,Runs,Wicket,Home_Team_Gujarat Lions,Home_Team_Kings XI Punjab,Home_Team_Kolkata Knight Riders,Home_Team_Mumbai Indians,...,Venue_Raipur,Venue_Rajkot,Venue_Visakhapatnam,Batting_Team_Gujarat Lions,Batting_Team_Kings XI Punjab,Batting_Team_Kolkata Knight Riders,Batting_Team_Mumbai Indians,Batting_Team_Rising Pune Supergiants,Batting_Team_Royal Challengers Bangalore,Batting_Team_Sunrisers Hyderabad
0,1,1,8,2,8,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,2,8,1,2,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,3,1,1,2,8,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,4,1,1,2,8,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,5,1,6,0,1,2,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
5,6,7,6,2,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,7,7,6,0,2,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
7,8,6,7,3,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
8,9,7,0,0,7,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,10,7,0,3,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
10,11,7,0,3,3,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
11,12,4,7,3,6,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
12,13,7,4,3,5,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,14,7,4,3,3,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
14,15,7,4,3,3,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
15,16,7,4,4,7,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
16,17,1,4,3,5,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
17,18,1,4,0,10,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,19,4,1,2,13,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,20,2,4,2,17,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
20,1,8,6,1,8,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
21,2,6,8,1,5,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
22,3,6,8,1,5,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
23,4,6,8,1,5,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
24,5,6,8,1,14,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
25,6,8,6,1,19,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
26,7,8,6,0,2,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
27,8,6,8,0,5,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
28,9,6,8,0,9,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
29,10,6,8,1,3,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2258,10,9,5,3,9,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2259,11,6,9,1,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2260,12,9,6,3,12,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2261,13,9,6,1,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2262,14,6,9,3,7,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2263,15,6,5,1,13,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2264,16,6,5,3,7,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2265,17,6,3,3,7,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2266,18,3,5,1,10,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2267,19,3,3,3,11,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2268,20,3,2,1,24,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2269,1,6,9,1,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2270,2,6,9,1,11,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2271,3,6,9,1,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2272,4,6,9,1,16,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2273,5,9,6,0,13,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2274,6,9,6,1,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2275,7,6,9,1,10,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2276,8,9,6,0,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2277,9,9,6,1,21,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2278,10,9,6,1,12,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2279,11,6,9,0,8,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2280,12,9,9,2,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2281,13,9,9,1,12,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2282,14,7,9,2,8,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2283,15,7,5,1,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2284,16,7,5,0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2285,17,5,4,1,10,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2286,18,2,4,1,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2287,19,2,4,1,11,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [12]:
dfr.to_csv("final.csv",index=False)

In [13]:

"""from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
colmn = ['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
X = dfr[colmn].values
y = dfr[["Runs","Wicket"]]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
dt.fit(X_train,y_train)
ypred = dt.predict(X_test)
y_test = y_test.values
np.mean(ypred==y_test)"""

'from sklearn.tree import DecisionTreeClassifier\ndt = DecisionTreeClassifier()\ncolmn = [\'Over\', \'Striker\', \'Non_Striker\', \'Bowler\',\n       \'Home_Team_Gujarat Lions\', \'Home_Team_Kings XI Punjab\',\n       \'Home_Team_Kolkata Knight Riders\', \'Home_Team_Mumbai Indians\',\n       \'Home_Team_Rising Pune Supergiants\',\n       \'Home_Team_Royal Challengers Bangalore\',\n       \'Home_Team_Sunrisers Hyderabad\', \'Away_Team_Gujarat Lions\',\n       \'Away_Team_Kings XI Punjab\', \'Away_Team_Kolkata Knight Riders\',\n       \'Away_Team_Mumbai Indians\', \'Away_Team_Rising Pune Supergiants\',\n       \'Away_Team_Royal Challengers Bangalore\',\n       \'Away_Team_Sunrisers Hyderabad\', \'Toss_Won_Gujarat Lions\',\n       \'Toss_Won_Kings XI Punjab\', \'Toss_Won_Kolkata Knight Riders\',\n       \'Toss_Won_Mumbai Indians\', \'Toss_Won_Rising Pune Supergiants\',\n       \'Toss_Won_Royal Challengers Bangalore\', \'Toss_Won_Sunrisers Hyderabad\',\n       \'Toss_Decision_field\', \'Venue_Chandigarh\', \'Venue_Delhi\',\n       \'Venue_Hyderabad\', \'Venue_Kanpur\', \'Venue_Kolkata\', \'Venue_Mumbai\',\n       \'Venue_Pune\', \'Venue_Raipur\', \'Venue_Rajkot\', \'Venue_Visakhapatnam\',\n       \'Batting_Team_Gujarat Lions\', \'Batting_Team_Kings XI Punjab\',\n       \'Batting_Team_Kolkata Knight Riders\', \'Batting_Team_Mumbai Indians\',\n       \'Batting_Team_Rising Pune Supergiants\',\n       \'Batting_Team_Royal Challengers Bangalore\',\n       \'Batting_Team_Sunrisers Hyderabad\']\nX = dfr[colmn].values\ny = dfr[["Runs","Wicket"]]\nfrom sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)\ndt.fit(X_train,y_train)\nypred = dt.predict(X_test)\ny_test = y_test.values\nnp.mean(ypred==y_test)'

In [14]:
import findspark

In [15]:
#initializing pyspark to the current working directory
findspark.init("/home/abhinav/spark-2.4.0-bin-hadoop2.7")

In [16]:
from pyspark.sql import SparkSession
#creating a spark session which is the entry point to a spark program
spark = SparkSession.builder.appName('phase3').getOrCreate()

In [107]:
import sparkconfig

In [17]:
#we are reading the csv that we generated above with the encoded columns
dataset = spark.read.csv("final.csv",header=True,inferSchema=True)

In [18]:
dataset.printSchema()

root
 |-- Over: integer (nullable = true)
 |-- Striker: integer (nullable = true)
 |-- Non_Striker: integer (nullable = true)
 |-- Bowler: integer (nullable = true)
 |-- Runs: integer (nullable = true)
 |-- Wicket: integer (nullable = true)
 |-- Home_Team_Gujarat Lions: integer (nullable = true)
 |-- Home_Team_Kings XI Punjab: integer (nullable = true)
 |-- Home_Team_Kolkata Knight Riders: integer (nullable = true)
 |-- Home_Team_Mumbai Indians: integer (nullable = true)
 |-- Home_Team_Rising Pune Supergiants: integer (nullable = true)
 |-- Home_Team_Royal Challengers Bangalore: integer (nullable = true)
 |-- Home_Team_Sunrisers Hyderabad: integer (nullable = true)
 |-- Away_Team_Gujarat Lions: integer (nullable = true)
 |-- Away_Team_Kings XI Punjab: integer (nullable = true)
 |-- Away_Team_Kolkata Knight Riders: integer (nullable = true)
 |-- Away_Team_Mumbai Indians: integer (nullable = true)
 |-- Away_Team_Rising Pune Supergiants: integer (nullable = true)
 |-- Away_Team_Royal Challengers Bangalore: integer (nullable = true)
 |-- Away_Team_Sunrisers Hyderabad: integer (nullable = true)
 |-- Toss_Won_Gujarat Lions: integer (nullable = true)
 |-- Toss_Won_Kings XI Punjab: integer (nullable = true)
 |-- Toss_Won_Kolkata Knight Riders: integer (nullable = true)
 |-- Toss_Won_Mumbai Indians: integer (nullable = true)
 |-- Toss_Won_Rising Pune Supergiants: integer (nullable = true)
 |-- Toss_Won_Royal Challengers Bangalore: integer (nullable = true)
 |-- Toss_Won_Sunrisers Hyderabad: integer (nullable = true)
 |-- Toss_Decision_field: integer (nullable = true)
 |-- Venue_Chandigarh: integer (nullable = true)
 |-- Venue_Delhi: integer (nullable = true)
 |-- Venue_Hyderabad: integer (nullable = true)
 |-- Venue_Kanpur: integer (nullable = true)
 |-- Venue_Kolkata: integer (nullable = true)
 |-- Venue_Mumbai: integer (nullable = true)
 |-- Venue_Pune: integer (nullable = true)
 |-- Venue_Raipur: integer (nullable = true)
 |-- Venue_Rajkot: integer (nullable = true)
 |-- Venue_Visakhapatnam: integer (nullable = true)
 |-- Batting_Team_Gujarat Lions: integer (nullable = true)
 |-- Batting_Team_Kings XI Punjab: integer (nullable = true)
 |-- Batting_Team_Kolkata Knight Riders: integer (nullable = true)
 |-- Batting_Team_Mumbai Indians: integer (nullable = true)
 |-- Batting_Team_Rising Pune Supergiants: integer (nullable = true)
 |-- Batting_Team_Royal Challengers Bangalore: integer (nullable = true)
 |-- Batting_Team_Sunrisers Hyderabad: integer (nullable = true)

In [19]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler

feat_cols = ['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
#features column is the one that we are using to train our decision tree models
vec_assembler_runs = VectorAssembler(inputCols = feat_cols, outputCol="features")
#Using VectorAssembler we are transforming the dataset into a vector

output_data = vec_assembler_runs.transform(dataset)
#we are using final_data_runs to get our run prediction
final_data_runs=output_data.select('features','Runs')  
#we are using final_data_wickets to get our wickets prediction

final_data_wickets = output_data.select('features','Wicket')

In [20]:
from pyspark.ml.classification import DecisionTreeClassifier

In [21]:
from pyspark.ml import Pipeline

In [22]:
#Creating our DECISION TREE CLASSIFIER object(one for predicting runs and the other for predicting wickets)
dtc = DecisionTreeClassifier(labelCol="Runs",featuresCol="features")
dtc_wicket = DecisionTreeClassifier(labelCol="Wicket",featuresCol="features")

In [23]:
#Fitting our training data to the decision tree classifier
#Creating 2 MODELS: one for predicting runs and the other for predicting wickets
dtc_runs_model = dtc.fit(final_data_runs)
dtc_wicket_model = dtc_wicket.fit(final_data_wickets)

In [114]:
def sim_match(bat_lineup,bowling_order,daf):
    """This function simulates the first innings of the match. 
        bat_lineup = It contains the batting order of the first innings of a match.List of 11 players
        bowling_order = It contains 20 entries. The index of the list indicates which player bowled the corresponding 
                        over
        daf = It is the dataframe that contains all the information regarding HomeTeam,AwayTeam,TossWon,TossDecision,BattingTeam
    """
    wickets = 0
    strike = bat_lineup[0]
    non_strike = bat_lineup[1]
    balls = 120
    if(strike in batclust.keys()):
        strikeclass = batclust[strike]
    else:
        strikeclass = 8
    if(non_strike in batclust.keys()):
        
        nonstrikeclass = batclust[non_strike]
    else:
        nonstrikeclass = 8
    #if(bat_class==-1):
     #   strike_conf = 50
    
        #strike_conf = sorted_run_class.index(bat_class)*10
    #strike_conf = sorted_run_class.index(class_by_name_bat(strike))*10
    """if(strike_conf<20):
        strike_conf = 20
    bat_class = class_by_name_bat(non_strike)
    if(bat_class==-1):
        non_strike_conf = 50
    else:
        non_strike_conf = sorted_run_class.index(bat_class)*10
    #non_strike_conf = sorted_run_class.index(class_by_name_bat(non_strike))*10
    if(non_strike_conf<20):
        non_strike_conf=20"""
   # bat_stat = dict()
    #bowl_stat = dict()
    # [runs,dots,4s,6s,balls,strike rate , out_by]
    #for i in bat_lineup:
     #   bat_stat[i] = [0,0,0,0,0,0, ""]
    #bat_stat[strike] = [0,0,0,0,0,0, ""] 
    #bat_stat[non_strike] = [0,0,0,0,0,0,""]
    
    #bowlers = list(set(bowling_order))
    #for i in bowlers:
        # [balls , runs , wickets , economy]
     #   bowl_stat[i] = [0,0,0,0]
    j = 0
    b_index = 2
    total = 0
    while(balls>=0 and wickets<10):
        if(j==20):
            break
        for i in range(1):
            if(balls<0):
                break
            bowlerpred = bowling_order[j]
            if(bowlerpred in bowlclust.keys()):
                
                bowlerclass = bowlclust[bowling_order[j]]
            else:
                if(j<=4 or j>=17):
                    bowlerclass = 4
                else:
                    bowlerclass = 3
            daf["Over"] = j
            daf["Striker"] = strikeclass
            daf["Non_Striker"] = nonstrikeclass
            daf["Bowler"] = bowlerclass
            
            tval = daf[['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']]
            
            tval.to_csv("ex.csv",index=False)
            tdata = pd.read_csv("ex.csv",usecols=['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad'])

            testdataset = spark.read.csv("ex.csv",header=True,inferSchema=True)
            output_tdata = vec_assembler_runs.transform(testdataset)
            final_data_runs=output_data.select('features','Runs') 
            final_data_wickets=output_data.select('features','Wicket') 
            #t_final_data_runs=output_tdata.select('features','Runs')  
           # anda = pd.read_csv("ex.csv")
            #t_final_data_wickets = output_tdata.select('features','Wicket')
            
            #vals = anda.iloc[0,:].values
            tout = dtc_runs_model.transform(final_data_runs)
            twicket = dtc_wicket_model.transform(final_data_wickets)
            outlist = tout.collect()
            wicketist = twicket.collect()
            runs = outlist[0][1] 
            wicket = wicketist[0][1]
            
           
            
            print(runs,wicket,strike,non_strike,bowling_order[j],balls)
            if(wicket!=0):
               
                #bat_stat[strike][1] = bat_stat[strike][1] + 1
                #bat_stat[strike][4] = bat_stat[strike][4] + 1
                #bat_stat[strike][5] = bat_stat[strike][0]/bat_stat[strike][4]*100
                #bat_stat[strike][-1] = bowling_order[j]
                #wickets = wickets+1
                #bowl_stat[bowling_order[j]][2] = 1 + bowl_stat[bowling_order[j]][2]
                #bowl_stat[bowling_order[j]][0] = 1 + bowl_stat[bowling_order[j]][0]
                #bowl_stat[bowling_order[j]][3] = bowl_stat[bowling_order[j]][1]/(bowl_stat[bowling_order[j]][0]/6)
                wickets+=wicket
                if(wickets>=10):
                    wickets = 10
                    break
                strike = bat_lineup[b_index]
                #bat_class = class_by_name_bat(strike)
                if(strike in batclust.keys()):
                    strikeclass = batclust[strike]
                else:
                    if(b_index>=9):
                        strikeclass = 0
                    else:
                        strikeclass = 9-b_index
                """if(bat_class==-1):
                    strike_conf = 50
                else:
                    strike_conf = sorted_run_class.index(bat_class)*10
                if(strike_conf<20):
                    strike_conf = 20"""
                
                total+=runs
                
                b_index = wicket+b_index
                #print(b_index)
                
            else:
               
                #bat_stat[strike][0] = bat_stat[strike][0] + runs
                # [runs,dots,4s,6s,balls,strike rate , out_by]
                #if(runs==0):
                #    bat_stat[strike][1] = bat_stat[strike][1] + 1
                #elif(runs==4):
                 #   bat_stat[strike][2] = bat_stat[strike][2] + 1
                #elif(runs==6):
                 #   bat_stat[strike][3] = bat_stat[strike][3] + 1
                #bat_stat[strike][4] = bat_stat[strike][4] + 1
                #bat_stat[strike][5] = bat_stat[strike][0]/bat_stat[strike][4]*100
                #strike_conf = strike_conf+k
                #bowl_stat[bowling_order[j]][0] = 1 + bowl_stat[bowling_order[j]][0]
                #bowl_stat[bowling_order[j]][1] = runs + bowl_stat[bowling_order[j]][1]
                #bowl_stat[bowling_order[j]][3] = bowl_stat[bowling_order[j]][1]/(bowl_stat[bowling_order[j]][0]/6)
            
            #if(wicket!=1 and runs%2!=0):
             #   #strike_conf = strike_conf+k
              #  strike,non_strike = non_strike,strike
               # strikeclass,nonstrikeclass = nonstrikeclass,strikeclass
                #strike_conf,non_strike_conf = non_strike_conf,strike_conf
                total+=runs
            balls = balls -6
            
        strike,non_strike = non_strike,strike
        strikeclass,nonstrikeclass = nonstrikeclass,strikeclass
        #strike_conf,non_strike_conf = non_strike_conf,strike_conf
        j = j+1
    
    #runs = sum([bat_stat[i][0] for i in bat_stat.keys()])
    #for i in bat_stat.keys():
    #    print(i)
    #print("\nFor batsman : [runs,dots,4s,6s,balls,strike rate , out_by]\n")
    #print(bat_stat)
    #print("\nFor bowler : [balls , runs , wickets , economy]\n")
    #print(bowl_stat)
    #print(runs)
    #print(wickets)
    return total,wickets

In [116]:
def sim_chase(bat_lineup,bowling_order,daf,target):
    wickets = 0
    strike = bat_lineup[0]
    non_strike = bat_lineup[1]
    balls = 120
    if(strike in batclust.keys()):
        strikeclass = batclust[strike]
    else:
        strikeclass = 8
    if(non_strike in batclust.keys()):
        
        nonstrikeclass = batclust[non_strike]
    else:
        nonstrikeclass = 8
    #if(bat_class==-1):
     #   strike_conf = 50
    
        #strike_conf = sorted_run_class.index(bat_class)*10
    #strike_conf = sorted_run_class.index(class_by_name_bat(strike))*10
    """if(strike_conf<20):
        strike_conf = 20
    bat_class = class_by_name_bat(non_strike)
    if(bat_class==-1):
        non_strike_conf = 50
    else:
        non_strike_conf = sorted_run_class.index(bat_class)*10
    #non_strike_conf = sorted_run_class.index(class_by_name_bat(non_strike))*10
    if(non_strike_conf<20):
        non_strike_conf=20"""
   # bat_stat = dict()
    #bowl_stat = dict()
    # [runs,dots,4s,6s,balls,strike rate , out_by]
    #for i in bat_lineup:
     #   bat_stat[i] = [0,0,0,0,0,0, ""]
    #bat_stat[strike] = [0,0,0,0,0,0, ""] 
    #bat_stat[non_strike] = [0,0,0,0,0,0,""]
    
    #bowlers = list(set(bowling_order))
    #for i in bowlers:
        # [balls , runs , wickets , economy]
     #   bowl_stat[i] = [0,0,0,0]
    j = 0
    b_index = 2
    total = 0
    while(balls>=0 and wickets<10):
        if(total>target):
            break
        if(j==20):
            break
        for i in range(1):
            if(balls<0):
                break
            bowlerpred = bowling_order[j]
            if(bowlerpred in bowlclust.keys()):
                
                bowlerclass = bowlclust[bowling_order[j]]
            else:
                if(j<=4 or j>=17):
                    bowlerclass = 4
                else:
                    bowlerclass = 3
            daf["Over"] = j
            daf["Striker"] = strikeclass
            daf["Non_Striker"] = nonstrikeclass
            daf["Bowler"] = bowlerclass
            
            tval = daf[['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']]
            
            tval.to_csv("ex.csv",index=False)
            tdata = pd.read_csv("ex.csv",usecols=['Over', 'Striker', 'Non_Striker', 'Bowler',
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad'])

            testdataset = spark.read.csv("ex.csv",header=True,inferSchema=True)
            output_tdata = vec_assembler_runs.transform(testdataset)
            final_data_runs=output_data.select('features','Runs') 
            final_data_wickets=output_data.select('features','Wicket') 
            #t_final_data_runs=output_tdata.select('features','Runs')  
           # anda = pd.read_csv("ex.csv")
            #t_final_data_wickets = output_tdata.select('features','Wicket')
            
            #vals = anda.iloc[0,:].values
            tout = dtc_runs_model.transform(final_data_runs)
            twicket = dtc_wicket_model.transform(final_data_wickets)
            outlist = tout.collect()
            wicketist = twicket.collect()
            runs = outlist[0][1] 
            wicket = wicketist[0][1]
            
            #update batsman and bowler stat
            #mapd = rwi()
            #for i in mapd.keys():
             #   if(j==i):
              #      wicket = mapd[i]
            print(runs,wicket,strike,non_strike,bowling_order[j],balls)
            if(wicket!=0):
               
                #bat_stat[strike][1] = bat_stat[strike][1] + 1
                #bat_stat[strike][4] = bat_stat[strike][4] + 1
                #bat_stat[strike][5] = bat_stat[strike][0]/bat_stat[strike][4]*100
                #bat_stat[strike][-1] = bowling_order[j]
                #wickets = wickets+1
                #bowl_stat[bowling_order[j]][2] = 1 + bowl_stat[bowling_order[j]][2]
                #bowl_stat[bowling_order[j]][0] = 1 + bowl_stat[bowling_order[j]][0]
                #bowl_stat[bowling_order[j]][3] = bowl_stat[bowling_order[j]][1]/(bowl_stat[bowling_order[j]][0]/6)
                wickets+=wicket
                if(wickets==10):
                    break
                strike = bat_lineup[b_index]
                #bat_class = class_by_name_bat(strike)
                if(strike in batclust.keys()):
                    strikeclass = batclust[strike]
                else:
                    if(b_index>=9):
                        strikeclass = 0
                    else:
                        strikeclass = 9-b_index
                """if(bat_class==-1):
                    strike_conf = 50
                else:
                    strike_conf = sorted_run_class.index(bat_class)*10
                if(strike_conf<20):
                    strike_conf = 20"""
                
                total+=runs
                if(total>target):
                    break
                b_index = wicket+b_index
                #print(b_index)
                
            else:
               
                #bat_stat[strike][0] = bat_stat[strike][0] + runs
                # [runs,dots,4s,6s,balls,strike rate , out_by]
                #if(runs==0):
                #    bat_stat[strike][1] = bat_stat[strike][1] + 1
                #elif(runs==4):
                 #   bat_stat[strike][2] = bat_stat[strike][2] + 1
                #elif(runs==6):
                 #   bat_stat[strike][3] = bat_stat[strike][3] + 1
                #bat_stat[strike][4] = bat_stat[strike][4] + 1
                #bat_stat[strike][5] = bat_stat[strike][0]/bat_stat[strike][4]*100
                #strike_conf = strike_conf+k
                #bowl_stat[bowling_order[j]][0] = 1 + bowl_stat[bowling_order[j]][0]
                #bowl_stat[bowling_order[j]][1] = runs + bowl_stat[bowling_order[j]][1]
                #bowl_stat[bowling_order[j]][3] = bowl_stat[bowling_order[j]][1]/(bowl_stat[bowling_order[j]][0]/6)
            
            #if(wicket!=1 and runs%2!=0):
             #   #strike_conf = strike_conf+k
              #  strike,non_strike = non_strike,strike
               # strikeclass,nonstrikeclass = nonstrikeclass,strikeclass
                #strike_conf,non_strike_conf = non_strike_conf,strike_conf
                total+=runs
                if(total>target):
                    break
            balls = balls -6
            
        strike,non_strike = non_strike,strike
        strikeclass,nonstrikeclass = nonstrikeclass,strikeclass
        #strike_conf,non_strike_conf = non_strike_conf,strike_conf
        j = j+1
    
    #runs = sum([bat_stat[i][0] for i in bat_stat.keys()])
    #for i in bat_stat.keys():
    #    print(i)
    #print("\nFor batsman : [runs,dots,4s,6s,balls,strike rate , out_by]\n")
    #print(bat_stat)
    #print("\nFor bowler : [balls , runs , wickets , economy]\n")
    #print(bowl_stat)
    #print(runs)
    #print(wickets)
    return total,wickets

In [26]:
#This is the columns that we will be using to predict
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]

In [39]:
#Simulating match #1 = RCB vs SRH
innings1 = [['DA Warner',
 'S Dhawan',
 'MC Henriques',
 'Yuvraj Singh',
 'DJ Hooda',
 'BCJ Cutting',
 'NV Ojha',
 'Bipul Sharma',
 'B Kumar',
 'BB Sran',
 'Mustafizur Rahman'],['S Aravind',
 'CH Gayle',
 'S Aravind',
 'CH Gayle',
 'SR Watson',
 'CH Gayle',
 'YS Chahal',
 'Iqbal Abdulla',
 'YS Chahal',
 'CJ Jordan',
 'SR Watson',
 'CJ Jordan',
 'YS Chahal',
 'S Aravind',
 'YS Chahal',
 'S Aravind',
 'CJ Jordan',
 'SR Watson',
 'CJ Jordan',
 'SR Watson']]

innings2 =[['CH Gayle',
 'V Kohli',
 'AB de Villiers',
 'KL Rahul',
 'SR Watson',
 'Sachin Baby',
 'STR Binny',
 'CJ Jordan',
 'Iqbal Abdulla',
 'S Arvind',
 'YS Chahal'],['B Kumar',
 'BB Sran',
 'B Kumar',
 'BB Sran',
 'BCJ Cutting',
 'Mustafizur Rahman',
 'MC Henriques',
 'BCJ Cutting',
 'MC Henriques',
 'Mustafizur Rahman',
 'BCJ Cutting',
 'Bipul Sharma',
 'BB Sran',
 'Bipul Sharma',
 'MC Henriques',
 'BCJ Cutting',
 'Mustafizur Rahman',
 'B Kumar',
 'Mustafizur Rahman',
 'B Kumar']]

In [40]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]

In [41]:
infa['Home_Team_Royal Challengers Bangalore']=1
infa['Away_Team_Sunrisers Hyderabad'] = 1
infa['Toss_Won_Sunrisers Hyderabad']=1
infa['Batting_Team_Sunrisers Hyderabad']=1
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
daf = pd.DataFrame.from_dict(infa)

In [42]:
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Sunrisers Hyderabad"] = 0
infa['Batting_Team_Royal Challengers Bangalore'] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

10 0 DA Warner S Dhawan S Aravind 120
9 0 S Dhawan DA Warner CH Gayle 114
9 0 DA Warner S Dhawan S Aravind 108
9 0 S Dhawan DA Warner CH Gayle 102
7 0 DA Warner S Dhawan SR Watson 96
6 1 S Dhawan DA Warner CH Gayle 90
10 0 DA Warner MC Henriques YS Chahal 84
10 1 MC Henriques DA Warner Iqbal Abdulla 78
7 0 DA Warner Yuvraj Singh YS Chahal 72
9 0 Yuvraj Singh DA Warner CJ Jordan 66
5 0 DA Warner Yuvraj Singh SR Watson 60
9 0 Yuvraj Singh DA Warner CJ Jordan 54
9 0 DA Warner Yuvraj Singh YS Chahal 48
9 0 Yuvraj Singh DA Warner S Aravind 42
6 0 DA Warner Yuvraj Singh YS Chahal 36
5 0 Yuvraj Singh DA Warner S Aravind 30
5 0 DA Warner Yuvraj Singh CJ Jordan 24
11 0 Yuvraj Singh DA Warner SR Watson 18
7 0 DA Warner Yuvraj Singh CJ Jordan 12
9 0 Yuvraj Singh DA Warner SR Watson 6
145 2
--------
10 0 CH Gayle V Kohli B Kumar 120
10 0 V Kohli CH Gayle BB Sran 114
10 0 CH Gayle V Kohli B Kumar 108
7 0 V Kohli CH Gayle BB Sran 102
6 0 CH Gayle V Kohli BCJ Cutting 96
6 0 V Kohli CH Gayle Mustafizur Rahman 90
9 0 CH Gayle V Kohli MC Henriques 84
10 0 V Kohli CH Gayle BCJ Cutting 78
6 0 CH Gayle V Kohli MC Henriques 72
9 0 V Kohli CH Gayle Mustafizur Rahman 66
7 1 CH Gayle V Kohli BCJ Cutting 60
11 1 V Kohli AB de Villiers Bipul Sharma 54
11 0 AB de Villiers KL Rahul BB Sran 48
11 0 KL Rahul AB de Villiers Bipul Sharma 42
10 0 AB de Villiers KL Rahul MC Henriques 36
10 0 KL Rahul AB de Villiers BCJ Cutting 30
6 0 AB de Villiers KL Rahul Mustafizur Rahman 24
6 0 KL Rahul AB de Villiers B Kumar 18
5 0 AB de Villiers KL Rahul Mustafizur Rahman 12
11 0 KL Rahul AB de Villiers B Kumar 6
153 2
--------
Chasing Team Wins

In [108]:
#Simulating Match #2 : DD vs MI
innings1 = [["P Shaw","GJ Maxwell","SS Iyer","RR Pant","V Shankar","Ankit Sharma","HV Patel","A Mishra","L Plunkett","S Lamichhane","TA Boult"],["KH Pandya","JJ Bumrah","HH Pandya","Mustafizur Rahman","JJ Bumrah","Mustafizur Rahman","M Markande","BCJ Cutting","M Markande","HH Pandya","BCJ Cutting","HH Pandya","BCJ Cutting","JJ Bumrah","Mustafizur Rahman","HH Pandya","KH Pandya","Mustafizur Rahman","JJ Bumrah","BCJ Cutting"]]


innings2 = [["AS Yadav","E Lewis","Ishan Kishan","KA Pollard","RG Sharma","KH Pandya","HH Pandya","BCJ Cutting","M Markande","JJ Bumrah","Mustafizur Rahman"],["S Lamichhane","TA Boult","GJ Maxwell","HV Patel","GJ Maxwell","L Plunkett","A Mishra","L Plunkett","A Mishra","S Lamichhane","A Mishra","S Lamichhane","TA Boult","HV Patel","A Mishra","S Lamichhane","TA Boult","L Plunkett","TA Boult","HV Patel"]]

In [111]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]
infa['Venue_Delhi']=1
infa['Away_Team_Mumbai Indians'] = 1

bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]

In [117]:
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa['Batting_Team_Mumbai Indians']=1
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

6 0 P Shaw GJ Maxwell KH Pandya 120
11 0 GJ Maxwell P Shaw JJ Bumrah 114
10 0 P Shaw GJ Maxwell HH Pandya 108
10 0 GJ Maxwell P Shaw Mustafizur Rahman 102
5 0 P Shaw GJ Maxwell JJ Bumrah 96
9 2 GJ Maxwell P Shaw Mustafizur Rahman 90
11 0 P Shaw SS Iyer M Markande 84
5 0 SS Iyer P Shaw BCJ Cutting 78
6 0 P Shaw SS Iyer M Markande 72
6 1 SS Iyer P Shaw HH Pandya 66
10 0 P Shaw V Shankar BCJ Cutting 60
9 0 V Shankar P Shaw HH Pandya 54
6 0 P Shaw V Shankar BCJ Cutting 48
5 0 V Shankar P Shaw JJ Bumrah 42
5 0 P Shaw V Shankar Mustafizur Rahman 36
6 0 V Shankar P Shaw HH Pandya 30
7 0 P Shaw V Shankar KH Pandya 24
10 0 V Shankar P Shaw Mustafizur Rahman 18
7 0 P Shaw V Shankar JJ Bumrah 12
7 0 V Shankar P Shaw BCJ Cutting 6
151 3
--------
5 0 AS Yadav E Lewis S Lamichhane 120
10 0 E Lewis AS Yadav TA Boult 114
10 0 AS Yadav E Lewis GJ Maxwell 108
7 0 E Lewis AS Yadav HV Patel 102
10 0 AS Yadav E Lewis GJ Maxwell 96
7 2 E Lewis AS Yadav L Plunkett 90
7 0 AS Yadav Ishan Kishan A Mishra 84
7 0 Ishan Kishan AS Yadav L Plunkett 78
11 0 AS Yadav Ishan Kishan A Mishra 72
11 0 Ishan Kishan AS Yadav S Lamichhane 66
6 1 AS Yadav Ishan Kishan A Mishra 60
6 0 Ishan Kishan RG Sharma S Lamichhane 54
6 1 RG Sharma Ishan Kishan TA Boult 48
10 2 Ishan Kishan KH Pandya HV Patel 42
5 0 KH Pandya HH Pandya A Mishra 36
11 0 HH Pandya KH Pandya S Lamichhane 30
5 0 KH Pandya HH Pandya TA Boult 24
9 0 HH Pandya KH Pandya L Plunkett 18
10 0 KH Pandya HH Pandya TA Boult 12
153 6
--------
Chasing Team Wins

In [46]:
#Simulating Match 3 - SRH vs KKR
innings1 =[["S Dhawan","SP Goswami","KS Williamson","MK Pandey","YK Pathan","CR Brathwaite","Shakib Al Hasan","Rashid Khan","B Kumar","S Kaul","Sandeep Sharma"],["N Rana","P Krishna","AD Russell","SP Narine","PP Chawla","SP Narine","Kuldeep Yadav","J Searles","Kuldeep Yadav","PP Chawla","Kuldeep Yadav","SP Narine","J Searles","Kuldeep Yadav","AD Russell","P Krishna","SP Narine","P Krishna","AD Russell","P Krishna"]]


innings2 = [["CA Lynn","SP Narine","RV Uthappa","KD Karthik","AD Russell","N Rana","S Gill","PP Chawla","J Searles","Kuldeep Yadav","P Krishna"],["B Kumar","Sandeep Sharma","S Kaul","","Shakib Al Hasan","B Kumar","S Kaul","Rashid Khan","CR Brathwaite","Rashid Khan","Shakib Al Hasan","Sandeep Sharma","Shakib Al Hasan","Rashid Khan","S Kaul","B Kumar","Rashid Khan","CR Brathwaite","S Kaul","B Kumar","CR Brathwaite"]]

In [47]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]

In [48]:
infa["Home_Team_Sunrisers Hyderabad"] = 1
infa["Away_Team_Kolkata Knight Riders"] = 1
infa["Toss_Won_Sunrisers Hyderabad"] = 1
infa["Batting_Team_Sunrisers Hyderabad"] = 1
daf = pd.DataFrame.from_dict(infa)

In [49]:
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]

In [50]:
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Sunrisers Hyderabad"] = 0
infa["Batting_Team_Kolkata Knight Riders"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

10 0 S Dhawan SP Goswami N Rana 120
9 0 SP Goswami S Dhawan P Krishna 114
7 0 S Dhawan SP Goswami AD Russell 108
7 0 SP Goswami S Dhawan SP Narine 102
9 0 S Dhawan SP Goswami PP Chawla 96
6 2 SP Goswami S Dhawan SP Narine 90
10 0 S Dhawan KS Williamson Kuldeep Yadav 84
5 0 KS Williamson S Dhawan J Searles 78
7 2 S Dhawan KS Williamson Kuldeep Yadav 72
6 1 KS Williamson YK Pathan PP Chawla 66
5 0 YK Pathan Shakib Al Hasan Kuldeep Yadav 60
11 2 Shakib Al Hasan YK Pathan SP Narine 54
5 0 YK Pathan Rashid Khan J Searles 48
9 0 Rashid Khan YK Pathan Kuldeep Yadav 42
9 1 YK Pathan Rashid Khan AD Russell 36
5 0 Rashid Khan S Kaul P Krishna 30
6 0 S Kaul Rashid Khan SP Narine 24
9 0 Rashid Khan S Kaul P Krishna 18
9 0 S Kaul Rashid Khan AD Russell 12
7 0 Rashid Khan S Kaul P Krishna 6
112 8
--------
7 0 CA Lynn SP Narine B Kumar 120
9 0 SP Narine CA Lynn Sandeep Sharma 114
6 0 CA Lynn SP Narine S Kaul 108
10 0 SP Narine CA Lynn  102
5 0 CA Lynn SP Narine Shakib Al Hasan 96
11 0 SP Narine CA Lynn B Kumar 90
11 2 CA Lynn SP Narine S Kaul 84
10 1 SP Narine RV Uthappa Rashid Khan 78
9 0 RV Uthappa AD Russell CR Brathwaite 72
10 0 AD Russell RV Uthappa Rashid Khan 66
11 1 RV Uthappa AD Russell Shakib Al Hasan 60
10 2 AD Russell N Rana Sandeep Sharma 54
5 0 N Rana S Gill Shakib Al Hasan 48
6 0 S Gill N Rana Rashid Khan 42
9 0 N Rana S Gill S Kaul 36
11 2 S Gill N Rana B Kumar 30
7 0 N Rana J Searles Rashid Khan 24
11 0 J Searles N Rana CR Brathwaite 18
6 0 N Rana J Searles S Kaul 12
6 0 J Searles N Rana B Kumar 6
117 8
--------
Chasing Team Wins

In [52]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]

In [53]:
#Simulating Match 4 - DD vs RCB
infa['Venue_Raipur'] = 1
infa['Away_Team_Royal Challengers Bangalore'] = 1
infa["Toss_Won_Royal Challengers Bangalore"] = 1
infa["Toss_Decision_field"] = 1
#56th match ipl 2016
innings1 = [['Q de Kock ', 'RR Pant', 'KK Nair', 'SV Samson', 'SW Billings', 'P Negi', 'CR Brathwaite', 'CH Morris', 'J Yadav', 'A Mishra', 'Z Khan'],['STR Binny', 'S Aravind', 'CJ Jordan', 'S Aravind', 'SR Watson', 'YS Chahal', 'STR Binny', 'YS Chahal', 'SR Watson', 'YS Chahal', 'Iqbal Abdulla', 'CJ Jordan', 'CH Gayle', 'S Aravind', 'CH Gayle', 'S Aravind', 'YS Chahal', 'SR Watson', 'Iqbal Abdulla', 'SR Watson']]

innings2=[['CH Gayle', 'V Kohli ', 'AB de Villiers', 'KL Rahul ', 'SR Watson', 'STR Binny', 'Sachin Baby ', 'CJ Jordan', 'Iqbal Abdulla', 'S Aravind', 'YS Chahal'],['Z Khan', 'CH Morris', 'Z Khan', 'CH Morris', 'Z Khan', 'CH Morris', 'P Negi', 'A Mishra', 'P Negi', 'J Yadav', 'CR Brathwaite', 'A Mishra', 'CR Brathwaite', 'A Mishra', 'P Negi', 'A Mishra', 'CR Brathwaite', 'Z Khan', 'CR Brathwaite', 'CH Morris']]
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Royal Challengers Bangalore"] = 1
#infa["Batting_Team_Kolkata Knight Riders"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

9 0 Q de Kock  RR Pant STR Binny 120
10 0 RR Pant Q de Kock  S Aravind 114
10 0 Q de Kock  RR Pant CJ Jordan 108
11 0 RR Pant Q de Kock  S Aravind 102
9 0 Q de Kock  RR Pant SR Watson 96
10 1 RR Pant Q de Kock  YS Chahal 90
5 1 Q de Kock  KK Nair STR Binny 84
9 0 KK Nair SV Samson YS Chahal 78
7 0 SV Samson KK Nair SR Watson 72
5 0 KK Nair SV Samson YS Chahal 66
11 0 SV Samson KK Nair Iqbal Abdulla 60
7 1 KK Nair SV Samson CJ Jordan 54
5 0 SV Samson SW Billings CH Gayle 48
9 0 SW Billings SV Samson S Aravind 42
7 1 SV Samson SW Billings CH Gayle 36
7 0 SW Billings P Negi S Aravind 30
7 0 P Negi SW Billings YS Chahal 24
6 0 SW Billings P Negi SR Watson 18
11 0 P Negi SW Billings Iqbal Abdulla 12
10 0 SW Billings P Negi SR Watson 6
136 4
--------
6 0 CH Gayle V Kohli  Z Khan 120
7 0 V Kohli  CH Gayle CH Morris 114
9 0 CH Gayle V Kohli  Z Khan 108
6 0 V Kohli  CH Gayle CH Morris 102
11 0 CH Gayle V Kohli  Z Khan 96
5 0 V Kohli  CH Gayle CH Morris 90
5 0 CH Gayle V Kohli  P Negi 84
9 0 V Kohli  CH Gayle A Mishra 78
11 0 CH Gayle V Kohli  P Negi 72
10 0 V Kohli  CH Gayle J Yadav 66
6 0 CH Gayle V Kohli  CR Brathwaite 60
7 1 V Kohli  CH Gayle A Mishra 54
11 0 CH Gayle AB de Villiers CR Brathwaite 48
9 0 AB de Villiers CH Gayle A Mishra 42
10 1 CH Gayle AB de Villiers P Negi 36
7 2 AB de Villiers KL Rahul  A Mishra 30
5 0 KL Rahul  SR Watson CR Brathwaite 24
11 0 SR Watson KL Rahul  Z Khan 18
9 0 KL Rahul  SR Watson CR Brathwaite 12
9 0 SR Watson KL Rahul  CH Morris 6
139 4
--------
Chasing Team Wins

In [54]:
#Simulating Match 5 - GL vs RCB
innings1 = [['AJ Finch', 'BB McCullum', 'SK Raina ', 'KD Karthik', 'DR Smith', 'RA Jadeja', 'DJ Bravo', 'ER Dwivedi', 'P Kumar', 'DS Kulkarni', 'SB Jakati'],['S Aravind', 'Iqbal Abdulla', 'S Aravind', 'SR Watson', 'Iqbal Abdulla', 'SR Watson', 'CJ Jordan', 'YS Chahal', 'STR Binny', 'YS Chahal', 'Iqbal Abdulla', 'YS Chahal', 'Iqbal Abdulla', 'CJ Jordan', 'S Aravind', 'SR Watson', 'YS Chahal', 'CJ Jordan', 'SR Watson', 'CJ Jordan']]

innings2 = [['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL Rahul', 'SR Watson', 'Sachin Baby', 'STR Binny', 'Iqbal Abdulla', 'CJ Jordan', 'S Aravind', 'YS Chahal'],['P Kumar', 'DS Kulkarni', 'P Kumar', 'DS Kulkarni', 'RA Jadeja', 'DS Kulkarni', 'RA Jadeja', 'DS Kulkarni', 'SB Jakati', 'RA Jadeja', 'SB Jakati', 'DJ Bravo', 'RA Jadeja', 'DJ Bravo', 'DR Smith', 'SB Jakati', 'P Kumar', 'DJ Bravo', 'P Kumar', 'DJ Bravo']]

In [55]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]


infa["Away_Team_Gujarat Lions"] = 1
infa["Toss_Won_Royal Challengers Bangalore"] = 1
infa["Toss_Decision_field"]=1
infa["Batting_Team_Gujarat Lions"] = 1
daf = pd.DataFrame.from_dict(infa)
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Gujarat Lions"] = 0
infa["Batting_Team_Royal Challengers Bangalore"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

10 0 AJ Finch BB McCullum S Aravind 120
7 0 BB McCullum AJ Finch Iqbal Abdulla 114
7 0 AJ Finch BB McCullum S Aravind 108
11 0 BB McCullum AJ Finch SR Watson 102
5 0 AJ Finch BB McCullum Iqbal Abdulla 96
5 1 BB McCullum AJ Finch SR Watson 90
7 0 AJ Finch SK Raina  CJ Jordan 84
11 1 SK Raina  AJ Finch YS Chahal 78
10 0 AJ Finch KD Karthik STR Binny 72
7 0 KD Karthik AJ Finch YS Chahal 66
5 2 AJ Finch KD Karthik Iqbal Abdulla 60
10 2 KD Karthik DR Smith YS Chahal 54
7 0 DR Smith DJ Bravo Iqbal Abdulla 48
6 0 DJ Bravo DR Smith CJ Jordan 42
6 2 DR Smith DJ Bravo S Aravind 36
10 0 DJ Bravo P Kumar SR Watson 30
11 0 P Kumar DJ Bravo YS Chahal 24
9 0 DJ Bravo P Kumar CJ Jordan 18
10 0 P Kumar DJ Bravo SR Watson 12
11 0 DJ Bravo P Kumar CJ Jordan 6
128 8
--------
6 0 CH Gayle V Kohli P Kumar 120
9 0 V Kohli CH Gayle DS Kulkarni 114
6 0 CH Gayle V Kohli P Kumar 108
7 0 V Kohli CH Gayle DS Kulkarni 102
5 0 CH Gayle V Kohli RA Jadeja 96
9 2 V Kohli CH Gayle DS Kulkarni 90
10 0 CH Gayle AB de Villiers RA Jadeja 84
10 0 AB de Villiers CH Gayle DS Kulkarni 78
9 0 CH Gayle AB de Villiers SB Jakati 72
5 0 AB de Villiers CH Gayle RA Jadeja 66
6 0 CH Gayle AB de Villiers SB Jakati 60
6 1 AB de Villiers CH Gayle DJ Bravo 54
5 0 CH Gayle SR Watson RA Jadeja 48
9 1 SR Watson CH Gayle DJ Bravo 42
11 0 CH Gayle Sachin Baby DR Smith 36
11 0 Sachin Baby CH Gayle SB Jakati 30
7 0 CH Gayle Sachin Baby P Kumar 24
9 0 Sachin Baby CH Gayle DJ Bravo 18
7 0 CH Gayle Sachin Baby P Kumar 12
9 0 Sachin Baby CH Gayle DJ Bravo 6
132 4
--------
Chasing Team Wins

In [70]:
#Simulating Match 6 - KXIP vs RPS

innings1 = [["HM AMla","M Vijay","WP Saha","Gurkeerat Singh","DA Miller","F Behardien","AR Patel","R Dhawan","KJ Abbott","MM Sharma","Sandeep Sharma"],["IK Pathan","AB Dinda","DL Chahar","AB Dinda","DL Chahar","NLTC Perera","IK Pathan","R Aswhin","A Zampa","R Aswhin","A Zampa","DL Chahar","A Zampa","IK Pathan","A Zampa","R Aswhin","IK Pathan","R Aswhin","AB Dinda","NLTC Perera"]]


innings2 = [["AM Rahane","UT Khawaja","GJ Bailey","SS Tiwary","MS Dhoni","IK Pathan","NLTC Perera","R Ashwin","A Zampa","AB Dinda","DL Chahar"],["Sandeep Sharma","MM Sharma","Sandeep Sharma","KJ Abbott","Sandeep Sharma","MM Sharma","AR Patel","Gurkeerat Singh","R Dhawan","KJ Abbott","R Dhawan","Gurkeerat Singh","AR Patel","R Dhawan","AR Patel","KJ Abbott","MM Sharma","Sandeep Sharma","MM Sharma","AR Patel"]]

In [71]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]
infa['Home_Team_Rising Pune Supergiants']=1
infa["Away_Team_Kings XI Punjab"] = 1
infa["Toss_Won_Kings XI Punjab"] = 1
infa["Venue_Vishakhapatnam"]=1
infa["Batting_Team_Kings XI Punjab"] = 1
daf = pd.DataFrame.from_dict(infa)
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Kings XI Punjab"] = 0
infa["Batting_Team_Rising Pune Supergiants"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

7 0 HM AMla M Vijay IK Pathan 120
7 0 M Vijay HM AMla AB Dinda 114
6 0 HM AMla M Vijay DL Chahar 108
11 0 M Vijay HM AMla AB Dinda 102
7 0 HM AMla M Vijay DL Chahar 96
7 0 M Vijay HM AMla NLTC Perera 90
10 2 HM AMla M Vijay IK Pathan 84
6 2 M Vijay WP Saha R Aswhin 78
7 1 WP Saha DA Miller A Zampa 72
6 0 DA Miller AR Patel R Aswhin 66
6 1 AR Patel DA Miller A Zampa 60
9 0 DA Miller R Dhawan DL Chahar 54
9 0 R Dhawan DA Miller A Zampa 48
5 0 DA Miller R Dhawan IK Pathan 42
9 0 R Dhawan DA Miller A Zampa 36
6 0 DA Miller R Dhawan R Aswhin 30
6 0 R Dhawan DA Miller IK Pathan 24
10 0 DA Miller R Dhawan R Aswhin 18
7 0 R Dhawan DA Miller AB Dinda 12
9 0 DA Miller R Dhawan NLTC Perera 6
121 6
--------
11 0 AM Rahane UT Khawaja Sandeep Sharma 120
9 0 UT Khawaja AM Rahane MM Sharma 114
9 0 AM Rahane UT Khawaja Sandeep Sharma 108
11 0 UT Khawaja AM Rahane KJ Abbott 102
6 0 AM Rahane UT Khawaja Sandeep Sharma 96
10 0 UT Khawaja AM Rahane MM Sharma 90
7 1 AM Rahane UT Khawaja AR Patel 84
11 0 UT Khawaja GJ Bailey Gurkeerat Singh 78
9 0 GJ Bailey UT Khawaja R Dhawan 72
7 2 UT Khawaja GJ Bailey KJ Abbott 66
9 0 GJ Bailey SS Tiwary R Dhawan 60
10 0 SS Tiwary GJ Bailey Gurkeerat Singh 54
11 0 GJ Bailey SS Tiwary AR Patel 48
10 0 SS Tiwary GJ Bailey R Dhawan 42
9 0 GJ Bailey SS Tiwary AR Patel 36
125 3
--------
Chasing Team Wins

In [88]:
##Simulating Match 7 - MI vs GL
innings1 = [["RG Sharma", "MJ Guptill","N Rana","KH Pandya","JC Buttler","KA Pollard","HH Pandya","Harbhajan Singh","R Vinay Kumar","MJ McClenaghan","JJ Bumrah"],["P Kumar","DS Kulkarni","P Kumar","DS Kulkarni","DR Smith","P Kumar","DR Smith","SB Jakati","DR Smith","DJ Bravo","RA Jadeja","DR Smith","SB Jakati","DJ Bravo","SB Jakati","DS Kulkarni","DJ Bravo","DS Kulkarni","DJ Bravo","P Kumar"]]

innings2 = [["AJ Finch","BB McCullum","SK Raina","KD Karthik","DR Smith","RA Jadeja","DJ Bravo","ER Dwivedi","SB Jakati","P Kumar","DS Kulkarni"],["R Vinay Kumar","JJ Bumrah","MJ McClenaghan","R Vinay Kumar","KH Pandya","JJ Bumrah","KH Pandya","Harbhajan Singh","MJ McClenaghan","Harbhajan Singh","R Vinay Kumar","Harbhajan Singh","JJ Bumrah","Harbhajan Singh","MJ McClenaghan","HH Pandya","JJ Bumrah","MJ McClenaghan","R Vinay Kumar","HH Pandya"]]

In [93]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]
infa['Home_Team_Royal Challengers Bangalore']=1
infa["Away_Team_Gujarat Lions"] = 1
infa["Toss_Won_Gujarat Lions"] = 1
infa["Toss_Decision_field"]=1
infa["Batting_Team_Gujarat Lions"] = 1
daf = pd.DataFrame.from_dict(infa)
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Gujarat Lions"] = 1
infa["Batting_Team_Royal Challengers Bangalore"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

10 0 RG Sharma MJ Guptill P Kumar 120
7 0 MJ Guptill RG Sharma DS Kulkarni 114
7 0 RG Sharma MJ Guptill P Kumar 108
11 0 MJ Guptill RG Sharma DS Kulkarni 102
5 0 RG Sharma MJ Guptill DR Smith 96
9 0 MJ Guptill RG Sharma P Kumar 90
7 0 RG Sharma MJ Guptill DR Smith 84
6 0 MJ Guptill RG Sharma SB Jakati 78
7 1 RG Sharma MJ Guptill DR Smith 72
10 0 MJ Guptill N Rana DJ Bravo 66
11 0 N Rana MJ Guptill RA Jadeja 60
7 0 MJ Guptill N Rana DR Smith 54
11 0 N Rana MJ Guptill SB Jakati 48
10 0 MJ Guptill N Rana DJ Bravo 42
10 0 N Rana MJ Guptill SB Jakati 36
11 0 MJ Guptill N Rana DS Kulkarni 30
6 0 N Rana MJ Guptill DJ Bravo 24
9 0 MJ Guptill N Rana DS Kulkarni 18
5 0 N Rana MJ Guptill DJ Bravo 12
6 0 MJ Guptill N Rana P Kumar 6
158 1
--------
5 0 AJ Finch BB McCullum R Vinay Kumar 120
5 0 BB McCullum AJ Finch JJ Bumrah 114
6 0 AJ Finch BB McCullum MJ McClenaghan 108
7 0 BB McCullum AJ Finch R Vinay Kumar 102
6 0 AJ Finch BB McCullum KH Pandya 96
6 2 BB McCullum AJ Finch JJ Bumrah 90
9 0 AJ Finch SK Raina KH Pandya 84
5 0 SK Raina AJ Finch Harbhajan Singh 78
9 0 AJ Finch SK Raina MJ McClenaghan 72
9 0 SK Raina AJ Finch Harbhajan Singh 66
7 0 AJ Finch SK Raina R Vinay Kumar 60
11 0 SK Raina AJ Finch Harbhajan Singh 54
10 0 AJ Finch SK Raina JJ Bumrah 48
6 0 SK Raina AJ Finch Harbhajan Singh 42
10 2 AJ Finch SK Raina MJ McClenaghan 36
10 0 SK Raina DR Smith HH Pandya 30
11 0 DR Smith SK Raina JJ Bumrah 24
11 0 SK Raina DR Smith MJ McClenaghan 18
10 0 DR Smith SK Raina R Vinay Kumar 12
10 0 SK Raina DR Smith HH Pandya 6
147 4
--------
Batting Team Wins

In [63]:
#Simulating Match 8 - GL vs SRH

innings1 =[['ER Dwivedi', 'BB McCullum', 'SK Raina', 'KD Karthik', 'AJ Finch', 'DR Smith', 'RA Jadeja', 'DJ Bravo', 'DS Kulkarni', 'P Kumar', 'S Kaushik'],['B Kumar', 'TA Boult', 'B Kumar', 'TA Boult', 'BB Sran', 'Bipul Sharma', 'BCJ Cutting', 'MC Henriques', 'Bipul Sharma', 'MC Henriques', 'BB Sran', 'Bipul Sharma', 'BCJ Cutting', 'MC Henriques', 'BB Sran', 'TA Boult', 'B Kumar', 'BCJ Cutting', 'TA Boult', 'B Kumar']]

innings2 = [['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh', 'DJ Hooda', 'BCJ Cutting', 'NV Ojha', 'Bipul Sharma', 'B Kumar', 'BB Sran', 'TA Boult'],['P Kumar', 'DS Kulkarni', 'P Kumar', 'DS Kulkarni', 'DR Smith', 'SK Raina', 'S Kaushik','SK Raina', 'S Kaushik', 'DJ Bravo', 'S Kaushik', 'DJ Bravo', 'S Kaushik', 'DS Kulkarni', 'DR Smith', 'DJ Bravo', 'P Kumar', 'DS Kulkarni', 'DJ Bravo', 'P Kumar']]

In [68]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]


infa["Toss_Won_Sunrisers Hyderabad"] = 1
infa["Toss_Decision_field"]=1
infa["Batting_Team_Gujarat Lions"] = 1
daf = pd.DataFrame.from_dict(infa)
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Gujarat Lions"] = 0
infa["Batting_Team_Sunrisers Hyderabad"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

7 0 ER Dwivedi BB McCullum B Kumar 120
9 0 BB McCullum ER Dwivedi TA Boult 114
7 0 ER Dwivedi BB McCullum B Kumar 108
5 0 BB McCullum ER Dwivedi TA Boult 102
9 0 ER Dwivedi BB McCullum BB Sran 96
6 0 BB McCullum ER Dwivedi Bipul Sharma 90
6 0 ER Dwivedi BB McCullum BCJ Cutting 84
11 0 BB McCullum ER Dwivedi MC Henriques 78
11 0 ER Dwivedi BB McCullum Bipul Sharma 72
5 1 BB McCullum ER Dwivedi MC Henriques 66
6 2 ER Dwivedi SK Raina BB Sran 60
7 2 SK Raina KD Karthik Bipul Sharma 54
10 0 KD Karthik DR Smith BCJ Cutting 48
11 0 DR Smith KD Karthik MC Henriques 42
9 0 KD Karthik DR Smith BB Sran 36
10 0 DR Smith KD Karthik TA Boult 30
10 0 KD Karthik DR Smith B Kumar 24
7 0 DR Smith KD Karthik BCJ Cutting 18
9 0 KD Karthik DR Smith TA Boult 12
9 0 DR Smith KD Karthik B Kumar 6
146 5
--------
9 0 DA Warner S Dhawan P Kumar 120
11 0 S Dhawan DA Warner DS Kulkarni 114
6 0 DA Warner S Dhawan P Kumar 108
7 0 S Dhawan DA Warner DS Kulkarni 102
11 0 DA Warner S Dhawan DR Smith 96
6 0 S Dhawan DA Warner SK Raina 90
10 0 DA Warner S Dhawan S Kaushik 84
11 0 S Dhawan DA Warner SK Raina 78
11 0 DA Warner S Dhawan S Kaushik 72
11 0 S Dhawan DA Warner DJ Bravo 66
11 0 DA Warner S Dhawan S Kaushik 60
9 0 S Dhawan DA Warner DJ Bravo 54
9 0 DA Warner S Dhawan S Kaushik 48
10 0 S Dhawan DA Warner DS Kulkarni 42
7 2 DA Warner S Dhawan DR Smith 36
7 0 S Dhawan MC Henriques DJ Bravo 30
9 0 MC Henriques S Dhawan P Kumar 24
148 2
--------
Chasing Team Wins

In [75]:
#Simulating Match 9 - KKR vs SRH
innings1 = [["RV Uthappa","G Gambhir","C Munro","MK Pandey","YK Pathan","JO Holder","Shakib Al Hasan","SA Yadav","AS Rajpoot", "SP Narine", "Kuldeep Yadav"],["B Kumar","BB Sran","B Kumar","BB Sran","KS Williamson","DJ Hooda","KV Sharma","DJ Hooda","KV Sharma","MC Henriques","Mustafizur Rahman","MC Henriques","Mustafizur Rahman","KV Sharma","BB Sran","B Kumar","Mustafizur Rahman","BB Sran","Mustafizur Rahman","B Kumar"]]

innings2 = [['S Dhawan','DA Warner ','NV Ojha ','Yuvraj Singh','KS Williamson','DJ Hooda','MC Henriques','KV Sharma', 'B Kumar','BB Sran', 'Mustafizur Rahman'],["YK Pathan","AS Rajpoot","Shakib Al Hasan","SP Narine","AS Rajpoot","SP Narine","JO Holder","C Munro","JO Holder","Kuldeep Yadav","Shakib Al Hasan","Kuldeep Yadav","SP Narine","Kuldeep Yadav","Shakib Al Hasan","Kuldeep Yadav","Shakib Al Hasan","SP Narine","JO Holder","AS Rajpoot"]]

In [76]:
ls =[
       'Home_Team_Gujarat Lions', 'Home_Team_Kings XI Punjab',
       'Home_Team_Kolkata Knight Riders', 'Home_Team_Mumbai Indians',
       'Home_Team_Rising Pune Supergiants',
       'Home_Team_Royal Challengers Bangalore',
       'Home_Team_Sunrisers Hyderabad', 'Away_Team_Gujarat Lions',
       'Away_Team_Kings XI Punjab', 'Away_Team_Kolkata Knight Riders',
       'Away_Team_Mumbai Indians', 'Away_Team_Rising Pune Supergiants',
       'Away_Team_Royal Challengers Bangalore',
       'Away_Team_Sunrisers Hyderabad', 'Toss_Won_Gujarat Lions',
       'Toss_Won_Kings XI Punjab', 'Toss_Won_Kolkata Knight Riders',
       'Toss_Won_Mumbai Indians', 'Toss_Won_Rising Pune Supergiants',
       'Toss_Won_Royal Challengers Bangalore', 'Toss_Won_Sunrisers Hyderabad',
       'Toss_Decision_field', 'Venue_Chandigarh', 'Venue_Delhi',
       'Venue_Hyderabad', 'Venue_Kanpur', 'Venue_Kolkata', 'Venue_Mumbai',
       'Venue_Pune', 'Venue_Raipur', 'Venue_Rajkot', 'Venue_Visakhapatnam',
       'Batting_Team_Gujarat Lions', 'Batting_Team_Kings XI Punjab',
       'Batting_Team_Kolkata Knight Riders', 'Batting_Team_Mumbai Indians',
       'Batting_Team_Rising Pune Supergiants',
       'Batting_Team_Royal Challengers Bangalore',
       'Batting_Team_Sunrisers Hyderabad']
infa = {}
for i in ls:
    infa[i] = [0]


infa["Toss_Won_Sunrisers Hyderabad"] = 1
infa['Venue_Kolkata']=1
infa["Toss_Decision_field"]=1
infa["Batting_Team_Kolkata Knight Riders"] = 1
daf = pd.DataFrame.from_dict(infa)
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Kolkata Knight Riders"] = 0
infa["Batting_Team_Sunrisers Hyderabad"] = 1
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

11 0 RV Uthappa G Gambhir B Kumar 120
9 0 G Gambhir RV Uthappa BB Sran 114
5 0 RV Uthappa G Gambhir B Kumar 108
5 0 G Gambhir RV Uthappa BB Sran 102
10 0 RV Uthappa G Gambhir KS Williamson 96
6 0 G Gambhir RV Uthappa DJ Hooda 90
11 1 RV Uthappa G Gambhir KV Sharma 84
10 0 G Gambhir C Munro DJ Hooda 78
5 0 C Munro G Gambhir KV Sharma 72
11 0 G Gambhir C Munro MC Henriques 66
9 0 C Munro G Gambhir Mustafizur Rahman 60
6 1 G Gambhir C Munro MC Henriques 54
7 0 C Munro MK Pandey Mustafizur Rahman 48
11 0 MK Pandey C Munro KV Sharma 42
9 0 C Munro MK Pandey BB Sran 36
5 0 MK Pandey C Munro B Kumar 30
7 0 C Munro MK Pandey Mustafizur Rahman 24
11 0 MK Pandey C Munro BB Sran 18
10 0 C Munro MK Pandey Mustafizur Rahman 12
7 0 MK Pandey C Munro B Kumar 6
148 2
--------
10 0 S Dhawan DA Warner  YK Pathan 120
11 0 DA Warner  S Dhawan AS Rajpoot 114
11 0 S Dhawan DA Warner  Shakib Al Hasan 108
9 0 DA Warner  S Dhawan SP Narine 102
7 0 S Dhawan DA Warner  AS Rajpoot 96
6 0 DA Warner  S Dhawan SP Narine 90
7 1 S Dhawan DA Warner  JO Holder 84
11 0 DA Warner  NV Ojha  C Munro 78
11 1 NV Ojha  DA Warner  JO Holder 72
9 0 DA Warner  Yuvraj Singh Kuldeep Yadav 66
6 0 Yuvraj Singh DA Warner  Shakib Al Hasan 60
10 2 DA Warner  Yuvraj Singh Kuldeep Yadav 54
6 0 Yuvraj Singh KS Williamson SP Narine 48
11 0 KS Williamson Yuvraj Singh Kuldeep Yadav 42
10 1 Yuvraj Singh KS Williamson Shakib Al Hasan 36
10 1 KS Williamson MC Henriques Kuldeep Yadav 30
5 0 MC Henriques KV Sharma Shakib Al Hasan 24
7 0 KV Sharma MC Henriques SP Narine 18
6 0 MC Henriques KV Sharma JO Holder 12
6 0 KV Sharma MC Henriques AS Rajpoot 6
121 6
--------
Batting Team Wins

In [77]:
#Simulating Match 10 - SRH vs RCB
#4th match ipl 2016

innings1 = [["CH Gayle","V Kohli","AB de Villiers","SR Watson","SN Khan","KM Jadhav","STR Binny","Parvez Rasool","HV Patel","AF Milne","YS Chahal"],["A Nehra","B Kumar","Mustafizur Rahman","A Nehra","B Kumar","Mustafizur Rahman","MC Henriques","KV Sharma","MC Henriques","KV Sharma","A Ashish Reddy","MC Henriques","KV Sharma","MC Henriques","A Ashish Reddy","B Kumar","KV Sharma","Mustafizur Rahman","B Kumar","Mustafizur Rahman"]]

innings2 = [["DA Warner","S Dhawan","MC Henriques","NV Ojha","DJ Hooda","EJG Morgan","A Ashish Reddy","KV Sharma","A Nehra","B Kumar","Mustafizur Rahman"],["AF Milne","SR Watson","AF Milne","Parvez Rasool","HV Patel","Parvez Rasool","HV Patel","YS Chahal","SR Watson","YS Chahal","AF Milne","YS Chahal","Parvez Rasool","YS Chahal","Parvez Rasool","SR Watson","HV Patel","AF Milne","HV Patel","SR Watson"]]

In [80]:
infa['Home_Team_Royal Challengers Bangalore']=1
infa['Away_Team_Sunrisers Hyderabad'] = 1
infa['Toss_Won_Sunrisers Hyderabad']=1
infa["Toss_Decision_field"]=1
infa['Batting_Team_Royal Challengers Bangalore']=1
bat1 = innings1[0]
bowl1 = innings1[1]
bat2 = innings2[0]
bowl2 = innings2[1]
daf = pd.DataFrame.from_dict(infa)
total,wickets = sim_match(bat1,bowl1,daf)
print(total,wickets)
print("--------")
infa["Batting_Team_Sunrisers Hyderabad"] = 1
infa['Batting_Team_Royal Challengers Bangalore'] = 0
daf = pd.DataFrame.from_dict(infa)
chase,wickets_c = sim_chase(bat2,bowl2,daf,total)
print(chase,wickets_c)
print("--------")
if(chase>total):
    print("Chasing Team Wins")
else:
    print("Batting Team Wins")

6 0 CH Gayle V Kohli A Nehra 120
11 0 V Kohli CH Gayle B Kumar 114
11 0 CH Gayle V Kohli Mustafizur Rahman 108
9 0 V Kohli CH Gayle A Nehra 102
10 0 CH Gayle V Kohli B Kumar 96
6 2 V Kohli CH Gayle Mustafizur Rahman 90
11 0 CH Gayle AB de Villiers MC Henriques 84
6 0 AB de Villiers CH Gayle KV Sharma 78
6 0 CH Gayle AB de Villiers MC Henriques 72
5 0 AB de Villiers CH Gayle KV Sharma 66
11 0 CH Gayle AB de Villiers A Ashish Reddy 60
6 0 AB de Villiers CH Gayle MC Henriques 54
9 0 CH Gayle AB de Villiers KV Sharma 48
9 0 AB de Villiers CH Gayle MC Henriques 42
10 0 CH Gayle AB de Villiers A Ashish Reddy 36
11 0 AB de Villiers CH Gayle B Kumar 30
9 0 CH Gayle AB de Villiers KV Sharma 24
6 0 AB de Villiers CH Gayle Mustafizur Rahman 18
5 0 CH Gayle AB de Villiers B Kumar 12
11 0 AB de Villiers CH Gayle Mustafizur Rahman 6
162 2
--------
9 0 DA Warner S Dhawan AF Milne 120
11 0 S Dhawan DA Warner SR Watson 114
10 0 DA Warner S Dhawan AF Milne 108
5 0 S Dhawan DA Warner Parvez Rasool 102
10 0 DA Warner S Dhawan HV Patel 96
7 1 S Dhawan DA Warner Parvez Rasool 90
6 0 DA Warner MC Henriques HV Patel 84
10 1 MC Henriques DA Warner YS Chahal 78
6 0 DA Warner NV Ojha SR Watson 72
9 0 NV Ojha DA Warner YS Chahal 66
11 0 DA Warner NV Ojha AF Milne 60
5 1 NV Ojha DA Warner YS Chahal 54
5 0 DA Warner DJ Hooda Parvez Rasool 48
7 0 DJ Hooda DA Warner YS Chahal 42
6 1 DA Warner DJ Hooda Parvez Rasool 36
9 2 DJ Hooda EJG Morgan SR Watson 30
11 0 EJG Morgan A Ashish Reddy HV Patel 24
9 0 A Ashish Reddy EJG Morgan AF Milne 18
7 0 EJG Morgan A Ashish Reddy HV Patel 12
9 0 A Ashish Reddy EJG Morgan SR Watson 6
125 6
--------
Batting Team Wins

In [106]:
match = [0,0,1,1,1,1,0,1,1,1,1]
onecount =0
for j in match:
    if(j==1):
        onecount+=1
else:
    accuracy = onecount/len(match)
print("Prediction Accuracy using Decision Trees {0} %".format(accuracy*100))

Prediction Accuracy using Decision Trees 72.72727272727273 %